name: DoSell Growth Hacking
favicon: null
layout_spectrum: 0.31960124033503234
typography_spectrum: 0.02705571474507451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4438063355628401
  lightness: 0.5992934089154005
  saturation: 0.9305483035277575
  rhythmicContrast: 0.9609112974721938
purpose: []
