layout_spectrum: 0.1063372353091836
typography_spectrum: 0.12368292384780943
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.8441758730914444
  lightness: 0.2746563015971333
  rhythmicContrast: 0.863956067012623
  saturation: 0.04453263687901199
opengraph: {}
analytics: {}
name: DoSell Growth Hacking
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Curated Growth Hacking
description: 'B2B Sales, Biz Dev., Growth Hacking'
purpose: []
