analytics: {}
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0.625
  lightness: 0.8125
  rhythmicContrast: 0.5625
  saturation: 0.767736
cta: {}
layout_spectrum: 0.44819
name: DoSell Growth Hacking
opengraph: {}
purpose: []
typography_spectrum: 0.134
