layout_spectrum: 0.603262054244296
typography_spectrum: 0.1510860830195027
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.5691156885742514
  lightness: 0.8334055723877863
  saturation: 0.6095407698178977
  rhythmicContrast: 1
coverPrefs:
  filter: false
name: LabShare Business
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a6474ee-823f-4a7a-9596-b7b9f0b578bf.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/597f7bf7-a00c-46fb-8983-6ccc191ef765.png
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/87ff0053-8e0f-4a07-bb29-5c2d564d4f81.jpg
purpose:
  - type: contact
    label: Contact me
    url: 'mailto:tibor.zahorecz@dosell.io'
  - type: external
    label: Global Market Access
    url: 'https://www.labsharegroup.com/'
title: LabShare Business
description: 'Digital Marketing, Growth Hacking, B2B Sales'
author:
  name: Tibor Zahorecz
  url: 'https://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
content_rating:
  adult: false
navigation:
  - name: Software Security Experts
    url: 'https://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/165a0d1c9f3465438e8ffb362a40e64461a1ea0d.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/165a0d1c9f3465438e8ffb362a40e64461a1ea0d.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/e5476136b3796d15c36aa38c3ecc0d56/noop.jpg?input=http%3A%2F%2F1u88jj3r4db2x4txp44yqfj1.wpengine.netdna-cdn.com%2Fwp-content%2Fuploads%2F2016%2F11%2FSan-Fransokyo-780x462.jpg
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: imgflo.herokuapp.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
