typography_spectrum: 0.2043759897351265
color:
  brandColors:
    - '#F3F3F3'
    - '#72797F'
    - '#12749B'
    - '#464749'
    - '#08252D'
  brandStrength: 0.7588570551015437
  lightness: 0.12347498605959117
  rhythmicContrast: 0.5824958018492907
  saturation: 0.4471877561882138
opengraph: {}
layout_spectrum: 0.4750988823361695
analytics: {}
name: DoSell Growth Hacking
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Curated Growth Hacking
purpose: []
