name: DoSell Growth Hacking
favicon: null
layout_spectrum: 0.94421
typography_spectrum: 0.134
title: 'BEST, CURATED ARTICLES, TOOLS OF GROWTH HACKING - DIGITAL MARKETING'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.650338
  lightness: 0.685811
  saturation: 0.767736
  rhythmicContrast: 0.5625
purpose: []
