typography_spectrum: 0.9853091675322503
color:
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
  brandStrength: 0.15187896136194468
  lightness: 0.5002904394641519
  rhythmicContrast: 0.8819015126209706
  saturation: 0.2689842174295336
opengraph: {}
layout_spectrum: 0.32190167950466275
analytics: {}
name: DoSell Growth Hacking
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Curated Growth Hacking
description: 'B2B Sales, Biz Dev., Growth Hacking'
purpose: []
