typography_spectrum: 0.6614218456670642
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.142018013400957
  lightness: 0.7643703380599618
  saturation: 0.42319846944883466
  rhythmicContrast: 0.2765155902598053
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/87ff0053-8e0f-4a07-bb29-5c2d564d4f81.jpg
layout_spectrum: 0.6044167676009238
analytics: {}
author:
  name: Tibor Zahorecz
  url: 'https://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/597f7bf7-a00c-46fb-8983-6ccc191ef765.png
name: LabShare Business
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'https://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a6474ee-823f-4a7a-9596-b7b9f0b578bf.png
title: LabShare Business
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/165a0d1c9f3465438e8ffb362a40e64461a1ea0d.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/165a0d1c9f3465438e8ffb362a40e64461a1ea0d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/e5476136b3796d15c36aa38c3ecc0d56/noop.jpg?input=http%3A%2F%2F1u88jj3r4db2x4txp44yqfj1.wpengine.netdna-cdn.com%2Fwp-content%2Fuploads%2F2016%2F11%2FSan-Fransokyo-780x462.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: 'Digital Marketing, Growth Hacking, B2B Sales'
purpose:
  - type: contact
    url: 'mailto:tibor.zahorecz@dosell.io'
    label: Contact me
  - type: external
    url: 'https://www.labsharegroup.com/'
    label: Global Market Access
url: 'https://labshare.business/'
github: true
