name: DoSell Growth Hacking
favicon: null
layout_spectrum: 0.01438
typography_spectrum: 0.23762
title: 'BEST, CURATED ARTICLES, TOOLS OF GROWTH HACKING - DIGITAL MARKETING'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.5625
purpose: []
