typography_spectrum: 0.23762
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.875
  rhythmicContrast: 0.5625
  saturation: 0.5625
opengraph: {}
layout_spectrum: 0.118243
analytics: {}
name: DoSell Growth Hacking
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Curated Growth Hacking
purpose: []
