name: DoSell Growth Hacking
favicon: null
layout_spectrum: 0.77834
typography_spectrum: 0.134
title: 'Best, curated articles, tools of Growth Hacking - Digital Marketing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9b7ff'
    - '#1a1727'
    - '#ff5c57'
    - '#696b7a'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.9305483035277575
  rhythmicContrast: 0.9609112974721938
purpose: []
