analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.546453
  lightness: 0.63598
  rhythmicContrast: 0.5625
  saturation: 0.767736
cta: {}
layout_spectrum: 0.873311
name: DoSell Growth Hacking
opengraph: {}
purpose: []
typography_spectrum: 0.134
