typography_spectrum: 0.7174753642175347
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.2805201532319188
  lightness: 0.8215351006947458
  rhythmicContrast: 0.5392198641784489
  saturation: 0.320824095280841
opengraph: {}
layout_spectrum: 0.7463329352904111
analytics: {}
name: DoSell Growth Hacking
cta: {}
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
title: Curated Growth Hacking
purpose: []
