typography_spectrum: 0.23762
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.875
  rhythmicContrast: 0.5625
  saturation: 0.5625
opengraph: {}
layout_spectrum: 0.118243
analytics: {}
name: DoSell Growth Hacking
cta: {}
title: Curated Growth Hacking
purpose: []
